### ISSUE TITLE
Resolute Export to Certware no longer works

### ISSUE THREAD

**Issue by juli1** [smaccm/smaccm#31]
When trying to export to Certware, I got the following error (see below). It looks like the associated eResource no longer exists. 

java.lang.NullPointerException
	at org.eclipse.xtext.ui.util.ResourceUtil.getFile(ResourceUtil.java:64)
	at com.rockwellcollins.atc.resolute.analysis.export.CertWareExport.getURI(CertWareExport.java:37)
	at com.rockwellcollins.atc.resolute.analysis.export.CertWareExport.export(CertWareExport.java:33)
	at com.rockwellcollins.atc.resolute.analysis.views.AssuranceCaseView$3.run(AssuranceCaseView.java:136)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by agacek** [comment]
I was not able to recreate this error. Can you provide more details? It
should just be doing a computation based on the file where the prove
statement is located.

-Andrew

**Comment by juli1** [comment]
I just run the resolute prove statement and right click on the result and select "Export to Certware". I am currently using the develop branch of OSATE and the sei_merge branch of smaccm.

**Comment by backesj** [comment]
Andrew,

What version of OSATE are you using? perhaps it's an issue on the develop
branch but not the master branch.

- John

**Comment by agacek** [comment]
I'm afraid we may have to wait until this problem manifests with
osate/master and either smaccm/master or smaccm/develop. The osate/develop
branch seems to have broken files in various packages which makes it not
compile. Also, I'm not really certain about the relationship between
sei_merge and smaccm/master or smaccm/develop.

**Comment by backesj** [comment]
Has this been resolved now that the SMACCM tools target OSATE 2.0.9?

**Comment by agacek** [comment]
I was not able to recreate the issue on Osate 2.0.9. Julien, does the
problem still happen for you?

**Comment by juli1** [comment]
For whatever reason, it seems ok now ... Let's close it!
